### ISSUE TITLE
 txindex configuration

### ISSUE THREAD

**Issue by xdpdavvv** [CounterpartyXCP/indexd-server#10]
Hello,
Is  txindex=1 required in bitcoin.conf to get accurate results from the indexd-server or does it purely rely on data from ZMQ?

Thanks.

**Comment by BramdeBoer** [comment]
If i remember correctly it is needed

**Comment by xdpdavvv** [comment]
Thanks for the reply. I setup my full node without itxindex=1 and indexd server is still getting correct results.  It took days for indexd to finish processing blocks and catch up to the latest block.

**Comment by BramdeBoer** [comment]
Good to know. Syncing is really slow indeed, if you find a faster alternative hit me up! :)

**Comment by backplanellc** [comment]
I also confirmed txindex=1 is **not** required. 

Sync time for me usually takes 3 full days and 132GB as of the current blockheight 515676

**Comment by chiguireitor** [comment]
txindex is not required for indexd afaik, but it's required for counterparty, so this is a non-issue for the project per-se.
