### ISSUE TITLE
Details in install steps

### ISSUE THREAD

**Issue by unsystemizer** [CounterpartyXCP/indexd-server#2]
I had to install a ton of extra npm packages: dotenv, express, debug and (after playing with Dockerfile) node-gyp, indexd, leveldown, qup, yajrpc, zmq, bitcoinjs-lib, run-parallel.
These probably can be added to README.md.

With that, and after following the steps from Dockerfile, indexd seems to start. I don't know yet if it does anything, I'm still syncing the blockchain, but I'll verify it works correctly and create a PR with more detail related to the installation procedure.

Another place which I don't understand well is the relationship between Bitcoin Core's ZMQ settings and .env - do the ports from bitcoin.conf need to map to ports from .env, etc.

**Comment by deweller** [comment]
`npm install` will install all the node dependencies.  I'm so used to that that I forgot to include it in the READM.

**Comment by unsystemizer** [comment]
Oh. Good. 

What about the parameters in .env, does one of them need to match `zmqpubhashtx` from bitcoin.conf? `zmqpubrawtx` (socket) I presume isn't necessary, although I pointed it to /data/index/indexd-testnet for my testnet setup... Bitcoind is still syncing so I can't tell whether this is correct.

How about txindex=1, do we still need that in bitcoin.conf? I need to rework Bitcoin Core install guide (later when we switch)

**Comment by qshuai** [comment]
What is your npm version?  I encountered a dependencies installation error. 
My env version: 
```
npm: 5.6.0
node: v9.11.2
```

**Comment by chiguireitor** [comment]
Try any even numbered nodejs version, as odd numbered are usually unstable non-lts supported versions that some packages don't deploy compatibility packages to.
Indexd dockerfile uses node-carbon, whic is equivalent to node 8 (on its latest minor version).
