### ISSUE TITLE
indexd fails without an error if db directory does not exist

### ISSUE THREAD

**Issue by ek1977** [CounterpartyXCP/indexd-server#20]
node index.js should throw an error if the database directory specified does not exist.  Instead it fails silently immediately upon startup with no apparent logging or output.

**Comment by chiguireitor** [comment]
Just tested this, when running it with `DEBUG=*` environment it throws an error:
`indexd_1  | Sun, 19 Jan 2020 04:40:24 GMT index Initialization failed: Error: IO error: /inexistent/directory/LOCK: No such file or directory`
This should be an issue only if the directory is incorrectly configured in the .env file
