### ISSUE TITLE
Lower RPCCONCURRENT or increase rpcworkqueue in Fednode?

### ISSUE THREAD

**Issue by unsystemizer** [CounterpartyXCP/indexd-server#3]
Got this in Core 0.15.1 debug.log (testnet) upon indexd-server startup. I'm using default parameters in bitcoin.conf. 

```
2017-10-28 14:08:36 WARNING: request rejected because http work queue depth exceeded, it can be increased with the -rpcworkqueue= setting
```

I'm not sure what's a "reasonable" setting here. 

I'd have to do some testing and comparisons to see (for example) how much worse is `RPCCONCURRENT=4` vs 8 vs 16 vs 32... 

We could do similar tests with rpcworkqueue, although personally I'd prefer to keep `RPCCONCURRENT` as low as possible, than adjust `rpcworkqueue` to a higher value.

**Comment by unsystemizer** [comment]
Just filled a Core issue number 11574 - `rpcworkqueue` is missing from `-h` output but it's a valid option. It seems the default is 16.

**Comment by deweller** [comment]
When I used these settings, those errors went away:
```
rpcthreads=16
rpcworkqueue=32
```

My gut says `RPCCONCURRENT` in indexd should be the same as `rpcworkqueue` in bitcoind.   So we should default RPCCONCURRENT to 16 instead of 32.

**Comment by deweller** [comment]
Closing this since this is more relevant to the federatednode repo.
