### ISSUE TITLE
Which nodejs version is recommended?

### ISSUE THREAD

**Issue by typoworx-de** [CounterpartyXCP/indexd-server#30]
Trying to build, but it fails to install/build node-gyp stuff (zmq) on node10 and 12?

**Comment by typoworx-de** [comment]
by the way a lot of used node-libs seem to be reported outdated ...

**Comment by jdogresorg** [comment]
indexd was depreciated a while ago in favor of addrindexrs.

If your trying to setup a Counterparty node, please do so through the 'federatednode' process, as it handles downloading, configuring and setting up an CP node and all components (Bitcoin, addrindexrs, counterparty, etc)

https://counterparty.io/docs/federated_node/

**Comment by typoworx-de** [comment]
Thanks having a look at it
