### ISSUE TITLE
spinSleepTime and minUptime values

### ISSUE THREAD

**Issue by unsystemizer** [CounterpartyXCP/indexd-server#7]
https://stackoverflow.com/questions/24921154/nodejs-forever-package-minuptime-and-spinsleeptime-warnings has an explanation on these values. 
I wonder if we should set these, and if we do whether spinSleepTime 60s is better than leaving restarts to Docker in which case we should document this for those who run it outside of Docker.

Edit: for those who want to test various options: https://github.com/CounterpartyXCP/indexd-server/blob/master/docker/start.sh `forever --optionN=valueN ./index.js`

**Comment by chiguireitor** [comment]
Yrah, but we don't use forever in production, so that's left for the specific environments of each user.
