### ISSUE TITLE
Indexd returned error: 400 Bad Request "Missing RPC response"

### ISSUE THREAD

**Issue by mandelmonkey** [CounterpartyXCP/indexd-server#9]
I made the following request to counterparty api

{"jsonrpc":"2.0","id":0,"method":"search_raw_transactions","params":{"address":"mqKy9agnNopat7WAsyzkgrJr5z5JisSzbz","unconfirmed":true}}

and sometimes the following error is thrown but sometimes it isnt and correct response is returned

{"id": 0, "jsonrpc": "2.0", "error": {"data": {"args": ["Indexd returned error: 400 Bad Request {\"error\":\"Missing RPC response\"}"], "type": "IndexdRPCError", "message": "Indexd returned error: 400 Bad Request {\"error\":\"Missing RPC response\"}"}, "code": -32000, "message": "Server error"}}

**Comment by jackzampolin** [comment]
@mandelmonkey Do you have `txindex=1` enabled on your `bitcoind` node? That RPC call is not supported by default.

**Comment by mandelmonkey** [comment]
yes its all set, the error is only sometimes, may have something to do with unconfirmed txs I suspect

**Comment by chiguireitor** [comment]
Closing as this error isn't seen in production atm
